config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batman_vs_superman'

  get 'pages/vote_batman'
  get 'pages/vote_superman'


  root 'pages#batman_vs_superman'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vote_batman.rb
class VoteBatman < ApplicationRecord
end

app/models/vote_superman.rb
class VoteSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  	render layout: 'layouts/bootstrap'
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end

  def batman_vs_superman
    @votes_superman = VoteSuperman.count
    @votes_batman = VoteBatman.count
  end

  def vote_batman
  	@name = params[:name]
  	@email = params[:email]

  	x = VoteBatman.new(name:@name, email:@email)
  	x.save

    redirect_to root_path 

  end

  def vote_superman
    @name = params[:name]
    @email = params[:email]

    x = VoteSuperman.new(name:@name, email:@email)
    x.save

    redirect_to root_path 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>

<h2>pika pika pikashu</h2>

<%= image_tag 'pika.jpg' %>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<div class="container <%= params[:controller]  %> <%= params[:action]  %>">
	<div class="row">
		<div class="col-md-12">
			<%= render "menu" %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experiment page</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" media="all" href="<%= asset_path 'bootstrap.css'%>">


  </head>
  
  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          
          <h1><code> yay! im bootstrap</code></h1>      

          <%= yield %>
        </div>
      </div>
    </div>
    
    
  </body>


  <script src="<%= asset_path 'bootstrap.js'%>"> </script>

</html>

app/views/pages/batman.html.erb
<div class="container" id="page-batman">
	<div class="row">
		<div class="col-md-12 full-height" >
			<h1 class="vcenter txt-batman">I am Batman</h1>
		</div>
	</div>
</div>

app/views/pages/batman_vs_superman.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6 col-xs-6 col-sm-6 side-batman">
			<%= link_to 'Página de Batman', pages_batman_path, :class=>'btn btn-info'  %>"

			<div class="row txt-white">
				<div class="col-md-offset-3 col-md-6">
				

				<form action="<%= pages_vote_batman_path %>" method="get" name="votebatman">

					<label for="name">Nombre</label>
					<input type="text" name="name" id="name" class="form-control">
					
					<label for="eame">Correo</label>
					<input type="text" name="email" id="email" class="form-control">
					
					<input type="submit" value="Votar por Batman" class="btn btn-info mg-t-20">
				</form>

	
				<p class="mg-t-20">
					<h4>Batman lleva <span class="badge badge-info"><%= @votes_batman %></span> votos </h4>
				</p>

				</div>


			</div>


		</div>
		<div class="col-md-6 col-xs-6 col-sm-6 side-superman">
			<%= link_to 'Página de Superman', pages_superman_path, :class=>'btn btn-danger'  %>"

			<div class="row txt-white">
				<div class="col-md-offset-3 col-md-6">
				

				<form action="<%= pages_vote_superman_path %>" method="get" name="votesuperman">

					<label for="name">Nombre</label>
					<input type="text" name="name" id="name" class="form-control">
					
					<label for="eame">Correo</label>
					<input type="text" name="email" id="email" class="form-control">
					
					<input type="submit" value="Votar por Superman" class="btn btn-danger mg-t-20">
				</form>

				<p class="mg-t-20">
					<h4>Superman lleva <span class="badge badge-info"><%= @votes_superman %></span> votos</h4> 
				</p>


				</div>
			</div>

		</div>
	</div>
</div>

app/views/pages/superman.html.erb
<div class="container" id="page-superman">
	<div class="row">
		<div class="col-md-12 full-height" >
			<h1 class="vcenter txt-superman">This looks like a job for Superman</h1>
		</div>
	</div>
</div>